name: Deploy Snowflake Changes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install schemachange
      run: |
        pip install schemachange

    - name: Deploy changes to Snowflake
      env:
        SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
        SF_DATABASE: ${{ secrets.SF_DATABASE }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_ROLE: ${{ secrets.SF_ROLE }}
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
        SF_SCHEMA: $( secrets.SF_SCHEMA }}
      run: |
        schemachange deploy \
          --snowflake-account "$SF_ACCOUNT" \
          --snowflake-database "$SF_DATABASE" \
          --snowflake-role "$SF_ROLE" \
          --snowflake-user "$SF_USERNAME" \
          --snowflake-warehouse "$SF_WAREHOUSE" \
          --snowflake-schema "$SF_SCHEMA" \
          --root-folder deploy \
          --change-history-table CHANGES.SCHEMA_CHANGE_HISTORY
