name: Deploy Snowflake Changes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install schemachange
      run: |
        pip install schemachange

    - name: Deploy changes to Snowflake
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
        SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
        SNOWFLAKE_USERNAME: ${{ secrets.SF_USERNAME }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
        SNOWFLAKE_SCHEMA: $( secrets.SF_SCHEMA }}
      run: |
        schemachange deploy \
          --snowflake-account "$SNOWFLAKE_ACCOUNT" \
          --snowflake-database "$SNOWFLAKE_DATABASE" \
          --snowflake-role "$SNOWFLAKE_ROLE" \
          --snowflake-user "$SNOWFLAKE_USERNAME" \
          --snowflake-warehouse "$SNOWFLAKE_WAREHOUSE" \
          --snowflake-schema "$SNOWFLAKE_SCHEMA" \
          --root-folder deploy \
          --change-history-table CHANGES.SCHEMA_CHANGE_HISTORY
